const MovieActionTypes = {

  GET_TRENDING_MOVIES_START: "GET_TRENDING_MOVIES_START",
  GET_TRENDING_MOVIES_SUCCESS: "GET_TRENDING_MOVIES_SUCCESS",
  GET_TRENDING_MOVIES_FAILURE: "GET_TRENDING_MOVIES_FAILURE",

  GET_POPULAR_MOVIES_START: "GET_POPULAR_MOVIES_START",
  GET_POPULAR_MOVIES_SUCCESS: "GET_POPULAR_MOVIES_SUCCESS",
  GET_POPULAR_MOVIES_FAILURE: "GET_POPULAR_MOVIES_FAILURE",

  GET_UPCOMING_MOVIES_START: "GET_UPCOMING_MOVIES_START",
  GET_UPCOMING_MOVIES_SUCCESS: "GET_UPCOMING_MOVIES_SUCCESS",
  GET_UPCOMING_MOVIES_FAILURE: "GET_UPCOMING_MOVIES_FAILURE",

  GET_TRENDING_MOVIES: "GET_TRENDING_MOVIES",
  GET_POPULAR_MOVIES: "GET_POPULAR_MOVIES",
  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
};

export default MovieActionTypes;
